name: CI
on:
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main
jobs:
    Setup-and-Local-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Setup Go environment
              uses: actions/setup-go@v5.3.0
              with:
                go-version: 'stable'
                check-latest: true
            - run: go version

            - name: build
              run: go build -o go-web-app

            - name: test
              run: go test ./...

    code-quality: 
      runs-on: ubuntu-latest
      steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6

    docker-build-and-push:
      needs: Setup-and-Local-Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4.2.2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Docker Login
          uses: docker/login-action@v3
          with:
              username: ${{ vars.DOCKERHUBUSERNAME}}
              password: ${{ secrets.DOCKERHUBPASSWORD }}
        - name: Build and Push action
          uses: docker/build-push-action@v6
          with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKERHUBUSERNAME }}/go-web-app:${{github.run_id}}

    update-newtag-in-helm-chart:
      runs-on: ubuntu-latest
      needs: docker-build-and-push
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}

        - name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app/values.yaml

        - name: Commit and push changes
          run: |
            git config --global user.email "rajamuneerbaigal@gmail.com"
            git config --global user.name "RajaMuneerBaigal"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push